<?php

namespace Database\Seeders;

use App\Models\ServiceInstruction;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use Carbon\Carbon;

use function Symfony\Component\Clock\now;

class ServiceInstructionSeeder extends Seeder
{
    public function run(): void
    {

        // $services = DB::table('services')->pluck('id')->toArray();
        DB::table('service_instructions')->insert([
            // [
            //     'id' => 1,
            //     'service_id' => 1,
            //     'instruction_title' => 'Service Fee',
            //     'instruction_description' => 'Computerized Certificate Issuance Fee is Rs. 100',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'deleted_at' => null,
            // ],
            // [
            //     'id' => 2,
            //     'service_id' => 3,
            //     'instruction_title' => 'Service Fee',
            //     'instruction_description' => 'Computerized Certificate Issuance Fee is Rs. 1,500',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'deleted_at' => null,
            // ],
            // [
            //     'id' => 3,
            //     'service_id' => 3,
            //     'instruction_title' => 'Delivery Time',
            //     'instruction_description' => 'Delivery Time For Copy Service Time at Facilitation Center for Delivery of Copy within 7 working days.',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'deleted_at' => null,
            // ],
            // [
            //     'id' => 4,
            //     'service_id' => 1,
            //     'instruction_title' => 'Center Timmings',
            //     'instruction_description' => 'E-Facilitation Center will be opened during 9:00 am to 5:00 pm.',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'deleted_at' => null,
            // ],

            [
                'id' => 1,
                'service_id' => 1,
                'instruction_title' => 'Service Fee',
                'instruction_description' => 'Computerized Certificate Issuance Fee is Rs. 100',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'service_id' => 3,
                'instruction_title' => 'Service Fee',
                'instruction_description' => 'Computerized Certificate Issuance Fee is Rs. 1,500',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'service_id' => 3,
                'instruction_title' => 'Delivery Time',
                'instruction_description' => 'Delivery Time For Copy Service Time at Facilitation Center for Delivery of Copy within 7 working days.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'service_id' => 3,
                'instruction_title' => 'Issuance Authority',
                'instruction_description' => 'AJK Interior Department is Issuance Authority for the Arms Licenses.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'service_id' => 3,
                'instruction_title' => 'Fee Payment',
                'instruction_description' => 'Fee Payment Mode should be Cash & in Pakistan Rupees (PKR).',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'service_id' => 1,
                'instruction_title' => 'Delivery Time For Copy',
                'instruction_description' => 'Service Time at e-Facilitation Center for Delivery of Copy within 60 days of birth 3 working days and in case of delay registration 61st to 7 years 7 working days.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'service_id' => 1,
                'instruction_title' => 'Delivery Time For Original Certificate',
                'instruction_description' => 'Service Time for Delivery of Original Certificate through Post within 60 Days of Birth 7 working days and in case of delay registration 61st-7 years 11 working days.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'service_id' => 1,
                'instruction_title' => 'Issuance Authority',
                'instruction_description' => 'This service will be issued by Secretary Union Council for birth within 60 days or Administrator / Nazim UC incase of delayed registration from 61st day to 7 years.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'service_id' => 1,
                'instruction_title' => 'Fee Payment Mode',
                'instruction_description' => 'Payment should be Cash & in Pakistan Rupees (PKR).',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'service_id' => 1,
                'instruction_title' => 'Designated Bank',
                'instruction_description' => 'Bank of Azad Jammu & Kashmir Pakistan.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'service_id' => 1,
                'instruction_title' => 'Center Timmings',
                'instruction_description' => 'E-Facilitation Center will be opened during 9:00 am to 5:00 pm.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'service_id' => 1,
                'instruction_title' => 'Center Timings',
                'instruction_description' => 'E-Facilitation Center will be opened from Monday to Saturday, during 9:00 am to 5:00 pm',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'service_id' => 1,
                'instruction_title' => 'Lunch Break',
                'instruction_description' => 'E-Facilitation Center will be closed for lunch during 01:00 pm to 02:00 pm.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'service_id' => 1,
                'instruction_title' => 'Jummah Break',
                'instruction_description' => 'E-Facilitation Center will be closed during 12:30 pm to 02:30 pm on Friday.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'service_id' => 2,
                'instruction_title' => 'Service Fee',
                'instruction_description' => 'Certificate Issuance Fee Rs.100',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'service_id' => 2,
                'instruction_title' => 'Delivery Time for Copy',
                'instruction_description' => 'Service Time at e Facilitation Center for Delivery of Copy is 3 working days.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'service_id' => 2,
                'instruction_title' => 'Delivery Time For Original Certificate',
                'instruction_description' => 'Service Time for Delivery of Original Certificate through Post is 6 working days',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'service_id' => 2,
                'instruction_title' => 'Issuance Authority',
                'instruction_description' => 'This service will issue by your Secretary Union Council.',
                'created_at' => now()   ,
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'service_id' => 2,
                'instruction_title' => 'In case of Late registration 61 days onward',
                'instruction_description' => 'All such cases shall be applied through court.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'service_id' => 2,
                'instruction_title' => 'Fee Payment Mode',
                'instruction_description' => 'Payment should be Cash & in Pakistan Rupees (PKR).',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'service_id' => 2,
                'instruction_title' => 'Designated Bank',
                'instruction_description' => 'Bank of Azad Jammu & Kashmir Pakistan.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'service_id' => 2,
                'instruction_title' => 'Center Timings',
                'instruction_description' => 'E-Facilitation Center will be opened from Monday to Saturday, during 9:00 am to 5:00 pm',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'service_id' => 2,
                'instruction_title' => 'Lunch Break',
                'instruction_description' => 'E-Facilitation Center will be closed for lunch during 01:00 pm to 02:00 pm.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'service_id' => 2,
                'instruction_title' => 'Jummah Break',
                'instruction_description' => 'E-Facilitation Center will be closed during 12:30 pm to 02:30 pm on Friday.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'service_id' => 5,
                'instruction_title' => 'Service Fee',
                'instruction_description' => 'You have to pay 200.00 Rs only as service charges',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'service_id' => 5,
                'instruction_title' => 'Delivery Time',
                'instruction_description' => 'Your certificate will be deliver with in 16 working days.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'service_id' => 5,
                'instruction_title' => 'Issuance Authority',
                'instruction_description' => 'This service will issue by your Relevant AC.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'service_id' => 5,
                'instruction_title' => 'Fee Payment Mode',
                'instruction_description' => 'Payment should be Cash & in Pakistan Rupees (PKR).',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'service_id' => 5,
                'instruction_title' => 'Designated Bank',
                'instruction_description' => 'Bank of Azad Jammu & Kashmir Pakistan.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'service_id' => 5,
                'instruction_title' => 'Center Timings',
                'instruction_description' => 'E-Facilitation Center will be opened from Monday to Saturday, during 9:00 am to 5:00 pm',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'service_id' => 5,
                'instruction_title' => 'Lunch Break',
                'instruction_description' => 'E-Facilitation Center will be closed for lunch during 01:00 pm to 02:00 pm.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'service_id' => 5,
                'instruction_title' => 'Jummah Break',
                'instruction_description' => 'E-Facilitation Center will be closed during 12:30 pm to 02:30 pm on Friday.',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'service_id' => 4,
                'instruction_title' => 'Service Fee',
                'instruction_description' => 'Computerized Certificate Issuance Fee is Rs. 100',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
